parameters:
    kayue_wordpress.table_prefix.subscriber.class: Kayue\WordpressBundle\Subscriber\TablePrefixSubscriber

services:
    kayue_wordpress.table_prefix.subscriber:
        class: '%kayue_wordpress.table_prefix.subscriber.class%'
        arguments:
            - '%kayue_wordpress.table_prefix%'
        tags:
            - { name: doctrine.event_subscriber }
